"""add_shark_tank_deal_fields

Revision ID: 36d9a78ae1f2
Revises: 5cef12d037bd
Create Date: 2026-07-26 17:59:23.642185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '36d9a78ae1f2'
down_revision: Union[str, Sequence[str], None] = '5cef12d037bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('startups', sa.Column('ask_amount', sa.Float(), nullable=True))
    op.add_column('startups', sa.Column('equity_offered', sa.Float(), nullable=True))
    op.add_column('startups', sa.Column('implied_valuation', sa.Float(), nullable=True))
    op.add_column('startups', sa.Column('use_of_funds', sa.String(), nullable=True))
    op.add_column('startups', sa.Column('mrr', sa.Float(), nullable=True))
    op.add_column('startups', sa.Column('growth_rate_pct', sa.Float(), nullable=True))
    op.add_column('startups', sa.Column('burn_rate', sa.Float(), nullable=True))
    op.add_column('startups', sa.Column('runway_months', sa.Integer(), nullable=True))
    op.add_column('startups', sa.Column('gross_margin_pct', sa.Float(), nullable=True))
    op.add_column('startups', sa.Column('total_raised', sa.Float(), nullable=True))
    op.add_column('startups', sa.Column('main_competitors', sa.String(), nullable=True))
    op.add_column('startups', sa.Column('moat_description', sa.Text(), nullable=True))
    op.add_column('startups', sa.Column('ai_score', sa.Integer(), nullable=True))
    op.add_column('startups', sa.Column('ai_verdict', sa.String(), nullable=True))
    op.add_column('startups', sa.Column('ai_score_breakdown', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('startups', 'ai_score_breakdown')
    op.drop_column('startups', 'ai_verdict')
    op.drop_column('startups', 'ai_score')
    op.drop_column('startups', 'moat_description')
    op.drop_column('startups', 'main_competitors')
    op.drop_column('startups', 'total_raised')
    op.drop_column('startups', 'gross_margin_pct')
    op.drop_column('startups', 'runway_months')
    op.drop_column('startups', 'burn_rate')
    op.drop_column('startups', 'growth_rate_pct')
    op.drop_column('startups', 'mrr')
    op.drop_column('startups', 'use_of_funds')
    op.drop_column('startups', 'implied_valuation')
    op.drop_column('startups', 'equity_offered')
    op.drop_column('startups', 'ask_amount')
    # ### end Alembic commands ###
