"""add_admin_review_revision_fields

Revision ID: df11c76f9f9d
Revises: 36d9a78ae1f2
Create Date: 2026-07-26 18:09:27.906380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df11c76f9f9d'
down_revision: Union[str, Sequence[str], None] = '36d9a78ae1f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('startups', sa.Column('approval_status', sa.String(), nullable=True))
    op.add_column('startups', sa.Column('has_pending_update', sa.Boolean(), nullable=True))
    op.add_column('startups', sa.Column('pending_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('startups', 'pending_data')
    op.drop_column('startups', 'has_pending_update')
    op.drop_column('startups', 'approval_status')
    # ### end Alembic commands ###
